// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 28 Oct 2025 01:24:27 -03.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package nk

/*
#include "nk.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// IncludeFontBaking as defined in nuklear/<predefined>:410
	IncludeFontBaking = 1
	// IncludeDefaultFont as defined in nuklear/<predefined>:411
	IncludeDefaultFont = 1
	// IncludeVertexBufferOutput as defined in nuklear/<predefined>:412
	IncludeVertexBufferOutput = 1
	// IncludeFixedTypes as defined in nuklear/<predefined>:413
	IncludeFixedTypes = 1
	// IncludeStandardIo as defined in nuklear/<predefined>:414
	IncludeStandardIo = 1
	// IncludeDefaultAllocator as defined in nuklear/<predefined>:415
	IncludeDefaultAllocator = 1
	// SingleFile as defined in nk/nuklear.h:221

	// NuklearH as defined in nk/nuklear.h:230

	// Undefined as defined in nk/nuklear.h:243
	Undefined = (-1.0)
	// UtfSize as defined in nk/nuklear.h:245
	UtfSize = 4
	// InputMax as defined in nk/nuklear.h:247
	InputMax = 16
	// MaxNumberBuffer as defined in nk/nuklear.h:250
	MaxNumberBuffer = 64
	// ScrollbarHidingTimeout as defined in nk/nuklear.h:253
	ScrollbarHidingTimeout = 4.0
	// Lib as defined in nk/nuklear.h:278
	Lib = 0x650840
	// FileLine as defined in nk/nuklear.h:309
	FileLine = 0x650840
	// Bool as defined in nk/nuklear.h:415
	Bool = 0x650840
	// WidgetDisabledFactor as defined in nk/nuklear.h:3850
	WidgetDisabledFactor = 0.5
	// Strtod as defined in nk/nuklear.h:4042
	Strtod = 0x650840
	// TexteditUndostatecount as defined in nk/nuklear.h:4527
	TexteditUndostatecount = 99
	// TexteditUndocharcount as defined in nk/nuklear.h:4531
	TexteditUndocharcount = 999
	// MaxLayoutRowTemplateColumns as defined in nk/nuklear.h:5605
	MaxLayoutRowTemplateColumns = 16
	// ChartMaxSlot as defined in nk/nuklear.h:5608
	ChartMaxSlot = 4
	// WindowMaxName as defined in nk/nuklear.h:5708
	WindowMaxName = 64
	// ButtonBehaviorStackSize as defined in nk/nuklear.h:5819
	ButtonBehaviorStackSize = 8
	// FontStackSize as defined in nk/nuklear.h:5823
	FontStackSize = 8
	// StyleItemStackSize as defined in nk/nuklear.h:5827
	StyleItemStackSize = 16
	// FloatStackSize as defined in nk/nuklear.h:5831
	FloatStackSize = 32
	// VectorStackSize as defined in nk/nuklear.h:5835
	VectorStackSize = 16
	// FlagsStackSize as defined in nk/nuklear.h:5839
	FlagsStackSize = 32
	// ColorStackSize as defined in nk/nuklear.h:5843
	ColorStackSize = 32
	// Float as defined in nk/nuklear.h:5857
	Float = 0x650840
	// ValuePageCapacity as defined in nk/nuklear.h:5887
	ValuePageCapacity = 0x650840
	// Pi as defined in nk/nuklear.h:5971
	Pi = 3.141592654
	// PiHalf as defined in nk/nuklear.h:5972
	PiHalf = 1.570796326
	// UtfInvalid as defined in nk/nuklear.h:5973
	UtfInvalid = 0xFFFD
	// MaxFloatPrecision as defined in nk/nuklear.h:5974
	MaxFloatPrecision = 2
)

const (
	// False as declared in nk/nuklear.h:483
	False = iota
	// True as declared in nk/nuklear.h:483
	True = 1
)

const (
	// Up as declared in nk/nuklear.h:497
	Up = iota
	// Right as declared in nk/nuklear.h:497
	Right = 1
	// Down as declared in nk/nuklear.h:497
	Down = 2
	// Left as declared in nk/nuklear.h:497
	Left = 3
)

const (
	// ButtonDefault as declared in nk/nuklear.h:498
	ButtonDefault = iota
	// ButtonRepeater as declared in nk/nuklear.h:498
	ButtonRepeater = 1
)

const (
	// Fixed as declared in nk/nuklear.h:499
	Fixed = False
	// Modifiable as declared in nk/nuklear.h:499
	Modifiable = True
)

const (
	// Vertical as declared in nk/nuklear.h:500
	Vertical = iota
	// Horizontal as declared in nk/nuklear.h:500
	Horizontal = 1
)

const (
	// Minimized as declared in nk/nuklear.h:501
	Minimized = False
	// Maximized as declared in nk/nuklear.h:501
	Maximized = True
)

const (
	// Hidden as declared in nk/nuklear.h:502
	Hidden = False
	// Shown as declared in nk/nuklear.h:502
	Shown = True
)

const (
	// ChartLines as declared in nk/nuklear.h:503
	ChartLines = iota
	// ChartColumn as declared in nk/nuklear.h:503
	ChartColumn = 1
	// ChartMax as declared in nk/nuklear.h:503
	ChartMax = 2
)

const (
	// ChartHovering as declared in nk/nuklear.h:504
	ChartHovering = 0x01
	// ChartClicked as declared in nk/nuklear.h:504
	ChartClicked = 0x02
)

const (
	// ColorFormatRGB as declared in nk/nuklear.h:505
	ColorFormatRGB = iota
	// ColorFormatRGBA as declared in nk/nuklear.h:505
	ColorFormatRGBA = 1
)

const (
	// PopupStatic as declared in nk/nuklear.h:506
	PopupStatic = iota
	// PopupDynamic as declared in nk/nuklear.h:506
	PopupDynamic = 1
)

const (
	// Dynamic as declared in nk/nuklear.h:507
	Dynamic = iota
	// Static as declared in nk/nuklear.h:507
	Static = 1
)

const (
	// TreeNode as declared in nk/nuklear.h:508
	TreeNode = iota
	// TreeTab as declared in nk/nuklear.h:508
	TreeTab = 1
)

const (
	// SymbolNone as declared in nk/nuklear.h:522
	SymbolNone = iota
	// SymbolX as declared in nk/nuklear.h:523
	SymbolX = 1
	// SymbolUnderscore as declared in nk/nuklear.h:524
	SymbolUnderscore = 2
	// SymbolCircleSolid as declared in nk/nuklear.h:525
	SymbolCircleSolid = 3
	// SymbolCircleOutline as declared in nk/nuklear.h:526
	SymbolCircleOutline = 4
	// SymbolRectSolid as declared in nk/nuklear.h:527
	SymbolRectSolid = 5
	// SymbolRectOutline as declared in nk/nuklear.h:528
	SymbolRectOutline = 6
	// SymbolTriangleUp as declared in nk/nuklear.h:529
	SymbolTriangleUp = 7
	// SymbolTriangleDown as declared in nk/nuklear.h:530
	SymbolTriangleDown = 8
	// SymbolTriangleLeft as declared in nk/nuklear.h:531
	SymbolTriangleLeft = 9
	// SymbolTriangleRight as declared in nk/nuklear.h:532
	SymbolTriangleRight = 10
	// SymbolPlus as declared in nk/nuklear.h:533
	SymbolPlus = 11
	// SymbolMinus as declared in nk/nuklear.h:534
	SymbolMinus = 12
	// SymbolTriangleUpOutline as declared in nk/nuklear.h:535
	SymbolTriangleUpOutline = 13
	// SymbolTriangleDownOutline as declared in nk/nuklear.h:536
	SymbolTriangleDownOutline = 14
	// SymbolTriangleLeftOutline as declared in nk/nuklear.h:537
	SymbolTriangleLeftOutline = 15
	// SymbolTriangleRightOutline as declared in nk/nuklear.h:538
	SymbolTriangleRightOutline = 16
	// SymbolMax as declared in nk/nuklear.h:539
	SymbolMax = 17
)

const (
	// KeyNone as declared in nk/nuklear.h:778
	KeyNone = iota
	// KeyShift as declared in nk/nuklear.h:779
	KeyShift = 1
	// KeyCtrl as declared in nk/nuklear.h:780
	KeyCtrl = 2
	// KeyDel as declared in nk/nuklear.h:781
	KeyDel = 3
	// KeyEnter as declared in nk/nuklear.h:782
	KeyEnter = 4
	// KeyTab as declared in nk/nuklear.h:783
	KeyTab = 5
	// KeyBackspace as declared in nk/nuklear.h:784
	KeyBackspace = 6
	// KeyCopy as declared in nk/nuklear.h:785
	KeyCopy = 7
	// KeyCut as declared in nk/nuklear.h:786
	KeyCut = 8
	// KeyPaste as declared in nk/nuklear.h:787
	KeyPaste = 9
	// KeyUp as declared in nk/nuklear.h:788
	KeyUp = 10
	// KeyDown as declared in nk/nuklear.h:789
	KeyDown = 11
	// KeyLeft as declared in nk/nuklear.h:790
	KeyLeft = 12
	// KeyRight as declared in nk/nuklear.h:791
	KeyRight = 13
	// KeyTextInsertMode as declared in nk/nuklear.h:793
	KeyTextInsertMode = 14
	// KeyTextReplaceMode as declared in nk/nuklear.h:794
	KeyTextReplaceMode = 15
	// KeyTextResetMode as declared in nk/nuklear.h:795
	KeyTextResetMode = 16
	// KeyTextLineStart as declared in nk/nuklear.h:796
	KeyTextLineStart = 17
	// KeyTextLineEnd as declared in nk/nuklear.h:797
	KeyTextLineEnd = 18
	// KeyTextStart as declared in nk/nuklear.h:798
	KeyTextStart = 19
	// KeyTextEnd as declared in nk/nuklear.h:799
	KeyTextEnd = 20
	// KeyTextUndo as declared in nk/nuklear.h:800
	KeyTextUndo = 21
	// KeyTextRedo as declared in nk/nuklear.h:801
	KeyTextRedo = 22
	// KeyTextSelectAll as declared in nk/nuklear.h:802
	KeyTextSelectAll = 23
	// KeyTextWordLeft as declared in nk/nuklear.h:803
	KeyTextWordLeft = 24
	// KeyTextWordRight as declared in nk/nuklear.h:804
	KeyTextWordRight = 25
	// KeyScrollStart as declared in nk/nuklear.h:806
	KeyScrollStart = 26
	// KeyScrollEnd as declared in nk/nuklear.h:807
	KeyScrollEnd = 27
	// KeyScrollDown as declared in nk/nuklear.h:808
	KeyScrollDown = 28
	// KeyScrollUp as declared in nk/nuklear.h:809
	KeyScrollUp = 29
	// KeyMax as declared in nk/nuklear.h:810
	KeyMax = 30
)

const (
	// ButtonLeft as declared in nk/nuklear.h:813
	ButtonLeft = iota
	// ButtonMiddle as declared in nk/nuklear.h:814
	ButtonMiddle = 1
	// ButtonRight as declared in nk/nuklear.h:815
	ButtonRight = 2
	// ButtonDouble as declared in nk/nuklear.h:816
	ButtonDouble = 3
	// ButtonMax as declared in nk/nuklear.h:817
	ButtonMax = 4
)

const (
	// AntiAliasingOff as declared in nk/nuklear.h:1189
	AntiAliasingOff = iota
	// AntiAliasingOn as declared in nk/nuklear.h:1189
	AntiAliasingOn = 1
)

const (
	// ConvertSuccess as declared in nk/nuklear.h:1191
	ConvertSuccess = iota
	// ConvertInvalidParam as declared in nk/nuklear.h:1192
	ConvertInvalidParam = 1
	// ConvertCommandBufferFull as declared in nk/nuklear.h:1193
	ConvertCommandBufferFull = (1 << (1))
	// ConvertVertexBufferFull as declared in nk/nuklear.h:1194
	ConvertVertexBufferFull = (1 << (2))
	// ConvertElementBufferFull as declared in nk/nuklear.h:1195
	ConvertElementBufferFull = (1 << (3))
)

const (
	// WindowBorder as declared in nk/nuklear.h:1508
	WindowBorder = (1 << (0))
	// WindowMovable as declared in nk/nuklear.h:1509
	WindowMovable = (1 << (1))
	// WindowScalable as declared in nk/nuklear.h:1510
	WindowScalable = (1 << (2))
	// WindowClosable as declared in nk/nuklear.h:1511
	WindowClosable = (1 << (3))
	// WindowMinimizable as declared in nk/nuklear.h:1512
	WindowMinimizable = (1 << (4))
	// WindowNoScrollbar as declared in nk/nuklear.h:1513
	WindowNoScrollbar = (1 << (5))
	// WindowTitle as declared in nk/nuklear.h:1514
	WindowTitle = (1 << (6))
	// WindowScrollAutoHide as declared in nk/nuklear.h:1515
	WindowScrollAutoHide = (1 << (7))
	// WindowBackground as declared in nk/nuklear.h:1516
	WindowBackground = (1 << (8))
	// WindowScaleLeft as declared in nk/nuklear.h:1517
	WindowScaleLeft = (1 << (9))
	// WindowNoInput as declared in nk/nuklear.h:1518
	WindowNoInput = (1 << (10))
)

const (
	// WidgetAlignLeft as declared in nk/nuklear.h:2430
	WidgetAlignLeft = 0x01
	// WidgetAlignCentered as declared in nk/nuklear.h:2431
	WidgetAlignCentered = 0x02
	// WidgetAlignRight as declared in nk/nuklear.h:2432
	WidgetAlignRight = 0x04
	// WidgetAlignTop as declared in nk/nuklear.h:2433
	WidgetAlignTop = 0x08
	// WidgetAlignMiddle as declared in nk/nuklear.h:2434
	WidgetAlignMiddle = 0x10
	// WidgetAlignBottom as declared in nk/nuklear.h:2435
	WidgetAlignBottom = 0x20
)

const (
	// WidgetLeft as declared in nk/nuklear.h:2438
	WidgetLeft = WidgetAlignMiddle | WidgetAlignLeft
	// WidgetCentered as declared in nk/nuklear.h:2439
	WidgetCentered = WidgetAlignMiddle | WidgetAlignCentered
	// WidgetRight as declared in nk/nuklear.h:2440
	WidgetRight = WidgetAlignMiddle | WidgetAlignRight
)

const (
	// WidgetInvalid as declared in nk/nuklear.h:3305
	WidgetInvalid = iota
	// WidgetValid as declared in nk/nuklear.h:3306
	WidgetValid = 1
	// WidgetRom as declared in nk/nuklear.h:3307
	WidgetRom = 2
	// WidgetDisabled as declared in nk/nuklear.h:3308
	WidgetDisabled = 3
)

const (
	// WidgetStateModified as declared in nk/nuklear.h:3311
	WidgetStateModified = (1 << (1))
	// WidgetStateInactive as declared in nk/nuklear.h:3312
	WidgetStateInactive = (1 << (2))
	// WidgetStateEntered as declared in nk/nuklear.h:3313
	WidgetStateEntered = (1 << (3))
	// WidgetStateHover as declared in nk/nuklear.h:3314
	WidgetStateHover = (1 << (4))
	// WidgetStateActived as declared in nk/nuklear.h:3315
	WidgetStateActived = (1 << (5))
	// WidgetStateLeft as declared in nk/nuklear.h:3316
	WidgetStateLeft = (1 << (6))
	// WidgetStateHovered as declared in nk/nuklear.h:3317
	WidgetStateHovered = WidgetStateHover | WidgetStateModified
	// WidgetStateActive as declared in nk/nuklear.h:3318
	WidgetStateActive = WidgetStateActived | WidgetStateModified
)

const (
	// TextAlignLeft as declared in nk/nuklear.h:3339
	TextAlignLeft = 0x01
	// TextAlignCentered as declared in nk/nuklear.h:3340
	TextAlignCentered = 0x02
	// TextAlignRight as declared in nk/nuklear.h:3341
	TextAlignRight = 0x04
	// TextAlignTop as declared in nk/nuklear.h:3342
	TextAlignTop = 0x08
	// TextAlignMiddle as declared in nk/nuklear.h:3343
	TextAlignMiddle = 0x10
	// TextAlignBottom as declared in nk/nuklear.h:3344
	TextAlignBottom = 0x20
)

const (
	// TextLeft as declared in nk/nuklear.h:3347
	TextLeft = TextAlignMiddle | TextAlignLeft
	// TextCentered as declared in nk/nuklear.h:3348
	TextCentered = TextAlignMiddle | TextAlignCentered
	// TextRight as declared in nk/nuklear.h:3349
	TextRight = TextAlignMiddle | TextAlignRight
)

const (
	// EditDefault as declared in nk/nuklear.h:3704
	EditDefault = iota
	// EditReadOnly as declared in nk/nuklear.h:3705
	EditReadOnly = (1 << (0))
	// EditAutoSelect as declared in nk/nuklear.h:3706
	EditAutoSelect = (1 << (1))
	// EditSigEnter as declared in nk/nuklear.h:3707
	EditSigEnter = (1 << (2))
	// EditAllowTab as declared in nk/nuklear.h:3708
	EditAllowTab = (1 << (3))
	// EditNoCursor as declared in nk/nuklear.h:3709
	EditNoCursor = (1 << (4))
	// EditSelectable as declared in nk/nuklear.h:3710
	EditSelectable = (1 << (5))
	// EditClipboard as declared in nk/nuklear.h:3711
	EditClipboard = (1 << (6))
	// EditCtrlEnterNewline as declared in nk/nuklear.h:3712
	EditCtrlEnterNewline = (1 << (7))
	// EditNoHorizontalScroll as declared in nk/nuklear.h:3713
	EditNoHorizontalScroll = (1 << (8))
	// EditAlwaysInsertMode as declared in nk/nuklear.h:3714
	EditAlwaysInsertMode = (1 << (9))
	// EditMultiline as declared in nk/nuklear.h:3715
	EditMultiline = (1 << (10))
	// EditGotoEndOnActivate as declared in nk/nuklear.h:3716
	EditGotoEndOnActivate = (1 << (11))
)

const (
	// EditSimple as declared in nk/nuklear.h:3719
	EditSimple = EditAlwaysInsertMode
	// EditField as declared in nk/nuklear.h:3720
	EditField = EditSimple | EditSelectable | EditClipboard
	// EditBox as declared in nk/nuklear.h:3721
	EditBox = EditAlwaysInsertMode | EditSelectable | EditMultiline | EditAllowTab | EditClipboard
	// EditEditor as declared in nk/nuklear.h:3722
	EditEditor = EditSelectable | EditMultiline | EditAllowTab | EditClipboard
)

const (
	// EditActive as declared in nk/nuklear.h:3725
	EditActive = (1 << (0))
	// EditInactive as declared in nk/nuklear.h:3726
	EditInactive = (1 << (1))
	// EditActivated as declared in nk/nuklear.h:3727
	EditActivated = (1 << (2))
	// EditDeactivated as declared in nk/nuklear.h:3728
	EditDeactivated = (1 << (3))
	// EditCommited as declared in nk/nuklear.h:3729
	EditCommited = (1 << (4))
)

const (
	// ColorText as declared in nk/nuklear.h:3853
	ColorText = iota
	// ColorWindow as declared in nk/nuklear.h:3854
	ColorWindow = 1
	// ColorHeader as declared in nk/nuklear.h:3855
	ColorHeader = 2
	// ColorBorder as declared in nk/nuklear.h:3856
	ColorBorder = 3
	// ColorButton as declared in nk/nuklear.h:3857
	ColorButton = 4
	// ColorButtonHover as declared in nk/nuklear.h:3858
	ColorButtonHover = 5
	// ColorButtonActive as declared in nk/nuklear.h:3859
	ColorButtonActive = 6
	// ColorToggle as declared in nk/nuklear.h:3860
	ColorToggle = 7
	// ColorToggleHover as declared in nk/nuklear.h:3861
	ColorToggleHover = 8
	// ColorToggleCursor as declared in nk/nuklear.h:3862
	ColorToggleCursor = 9
	// ColorSelect as declared in nk/nuklear.h:3863
	ColorSelect = 10
	// ColorSelectActive as declared in nk/nuklear.h:3864
	ColorSelectActive = 11
	// ColorSlider as declared in nk/nuklear.h:3865
	ColorSlider = 12
	// ColorSliderCursor as declared in nk/nuklear.h:3866
	ColorSliderCursor = 13
	// ColorSliderCursorHover as declared in nk/nuklear.h:3867
	ColorSliderCursorHover = 14
	// ColorSliderCursorActive as declared in nk/nuklear.h:3868
	ColorSliderCursorActive = 15
	// ColorProperty as declared in nk/nuklear.h:3869
	ColorProperty = 16
	// ColorEdit as declared in nk/nuklear.h:3870
	ColorEdit = 17
	// ColorEditCursor as declared in nk/nuklear.h:3871
	ColorEditCursor = 18
	// ColorCombo as declared in nk/nuklear.h:3872
	ColorCombo = 19
	// ColorChart as declared in nk/nuklear.h:3873
	ColorChart = 20
	// ColorChartColor as declared in nk/nuklear.h:3874
	ColorChartColor = 21
	// ColorChartColorHighlight as declared in nk/nuklear.h:3875
	ColorChartColorHighlight = 22
	// ColorScrollbar as declared in nk/nuklear.h:3876
	ColorScrollbar = 23
	// ColorScrollbarCursor as declared in nk/nuklear.h:3877
	ColorScrollbarCursor = 24
	// ColorScrollbarCursorHover as declared in nk/nuklear.h:3878
	ColorScrollbarCursorHover = 25
	// ColorScrollbarCursorActive as declared in nk/nuklear.h:3879
	ColorScrollbarCursorActive = 26
	// ColorTabHeader as declared in nk/nuklear.h:3880
	ColorTabHeader = 27
	// ColorKnob as declared in nk/nuklear.h:3881
	ColorKnob = 28
	// ColorKnobCursor as declared in nk/nuklear.h:3882
	ColorKnobCursor = 29
	// ColorKnobCursorHover as declared in nk/nuklear.h:3883
	ColorKnobCursorHover = 30
	// ColorKnobCursorActive as declared in nk/nuklear.h:3884
	ColorKnobCursorActive = 31
	// ColorCount as declared in nk/nuklear.h:3885
	ColorCount = 32
)

const (
	// CursorArrow as declared in nk/nuklear.h:3888
	CursorArrow = iota
	// CursorText as declared in nk/nuklear.h:3889
	CursorText = 1
	// CursorMove as declared in nk/nuklear.h:3890
	CursorMove = 2
	// CursorResizeVertical as declared in nk/nuklear.h:3891
	CursorResizeVertical = 3
	// CursorResizeHorizontal as declared in nk/nuklear.h:3892
	CursorResizeHorizontal = 4
	// CursorResizeTopLeftDownRight as declared in nk/nuklear.h:3893
	CursorResizeTopLeftDownRight = 5
	// CursorResizeTopRightDownLeft as declared in nk/nuklear.h:3894
	CursorResizeTopRightDownLeft = 6
	// CursorCount as declared in nk/nuklear.h:3895
	CursorCount = 7
)

const (
	// CoordUv as declared in nk/nuklear.h:4241
	CoordUv = iota
	// CoordPixel as declared in nk/nuklear.h:4242
	CoordPixel = 1
)

const (
	// FontAtlasAlpha8 as declared in nk/nuklear.h:4296
	FontAtlasAlpha8 = iota
	// FontAtlasRgba32 as declared in nk/nuklear.h:4297
	FontAtlasRgba32 = 1
)

const (
	// BufferFixed as declared in nk/nuklear.h:4396
	BufferFixed = iota
	// BufferDynamic as declared in nk/nuklear.h:4397
	BufferDynamic = 1
)

const (
	// BufferFront as declared in nk/nuklear.h:4401
	BufferFront = iota
	// BufferBack as declared in nk/nuklear.h:4402
	BufferBack = 1
	// BufferMax as declared in nk/nuklear.h:4403
	BufferMax = 2
)

const (
	// TextEditSingleLine as declared in nk/nuklear.h:4558
	TextEditSingleLine = iota
	// TextEditMultiLine as declared in nk/nuklear.h:4559
	TextEditMultiLine = 1
)

const (
	// TextEditModeView as declared in nk/nuklear.h:4563
	TextEditModeView = iota
	// TextEditModeInsert as declared in nk/nuklear.h:4564
	TextEditModeInsert = 1
	// TextEditModeReplace as declared in nk/nuklear.h:4565
	TextEditModeReplace = 2
)

const (
	// CommandTypeNop as declared in nk/nuklear.h:4668
	CommandTypeNop = iota
	// CommandTypeScissor as declared in nk/nuklear.h:4669
	CommandTypeScissor = 1
	// CommandTypeLine as declared in nk/nuklear.h:4670
	CommandTypeLine = 2
	// CommandTypeCurve as declared in nk/nuklear.h:4671
	CommandTypeCurve = 3
	// CommandTypeRect as declared in nk/nuklear.h:4672
	CommandTypeRect = 4
	// CommandTypeRectFilled as declared in nk/nuklear.h:4673
	CommandTypeRectFilled = 5
	// CommandTypeRectMultiColor as declared in nk/nuklear.h:4674
	CommandTypeRectMultiColor = 6
	// CommandTypeCircle as declared in nk/nuklear.h:4675
	CommandTypeCircle = 7
	// CommandTypeCircleFilled as declared in nk/nuklear.h:4676
	CommandTypeCircleFilled = 8
	// CommandTypeArc as declared in nk/nuklear.h:4677
	CommandTypeArc = 9
	// CommandTypeArcFilled as declared in nk/nuklear.h:4678
	CommandTypeArcFilled = 10
	// CommandTypeTriangle as declared in nk/nuklear.h:4679
	CommandTypeTriangle = 11
	// CommandTypeTriangleFilled as declared in nk/nuklear.h:4680
	CommandTypeTriangleFilled = 12
	// CommandTypePolygon as declared in nk/nuklear.h:4681
	CommandTypePolygon = 13
	// CommandTypePolygonFilled as declared in nk/nuklear.h:4682
	CommandTypePolygonFilled = 14
	// CommandTypePolyline as declared in nk/nuklear.h:4683
	CommandTypePolyline = 15
	// CommandTypeText as declared in nk/nuklear.h:4684
	CommandTypeText = 16
	// CommandTypeImage as declared in nk/nuklear.h:4685
	CommandTypeImage = 17
	// CommandTypeCustom as declared in nk/nuklear.h:4686
	CommandTypeCustom = 18
)

const (
	// ClippingOff as declared in nk/nuklear.h:4851
	ClippingOff = False
	// ClippingOn as declared in nk/nuklear.h:4852
	ClippingOn = True
)

const (
	// StrokeOpen as declared in nk/nuklear.h:4972
	StrokeOpen = False
	// StrokeClosed as declared in nk/nuklear.h:4973
	StrokeClosed = True
)

const (
	// VertexPosition as declared in nk/nuklear.h:4977
	VertexPosition = iota
	// VertexColor as declared in nk/nuklear.h:4978
	VertexColor = 1
	// VertexTexcoord as declared in nk/nuklear.h:4979
	VertexTexcoord = 2
	// VertexAttributeCount as declared in nk/nuklear.h:4980
	VertexAttributeCount = 3
)

const (
	// FormatSchar as declared in nk/nuklear.h:4984
	FormatSchar = iota
	// FormatSshort as declared in nk/nuklear.h:4985
	FormatSshort = 1
	// FormatSint as declared in nk/nuklear.h:4986
	FormatSint = 2
	// FormatUchar as declared in nk/nuklear.h:4987
	FormatUchar = 3
	// FormatUshort as declared in nk/nuklear.h:4988
	FormatUshort = 4
	// FormatUint as declared in nk/nuklear.h:4989
	FormatUint = 5
	// FormatFloat as declared in nk/nuklear.h:4990
	FormatFloat = 6
	// FormatDouble as declared in nk/nuklear.h:4991
	FormatDouble = 7
	// FormatColorBegin as declared in nk/nuklear.h:4993
	FormatColorBegin = 8
	// FormatR8g8b8 as declared in nk/nuklear.h:4994
	FormatR8g8b8 = FormatColorBegin
	// FormatR16g15b16 as declared in nk/nuklear.h:4995
	FormatR16g15b16 = 9
	// FormatR32g32b32 as declared in nk/nuklear.h:4996
	FormatR32g32b32 = 10
	// FormatR8g8b8a8 as declared in nk/nuklear.h:4998
	FormatR8g8b8a8 = 11
	// FormatB8g8r8a8 as declared in nk/nuklear.h:4999
	FormatB8g8r8a8 = 12
	// FormatR16g15b16a16 as declared in nk/nuklear.h:5000
	FormatR16g15b16a16 = 13
	// FormatR32g32b32a32 as declared in nk/nuklear.h:5001
	FormatR32g32b32a32 = 14
	// FormatR32g32b32a32Float as declared in nk/nuklear.h:5002
	FormatR32g32b32a32Float = 15
	// FormatR32g32b32a32Double as declared in nk/nuklear.h:5003
	FormatR32g32b32a32Double = 16
	// FormatRgb32 as declared in nk/nuklear.h:5005
	FormatRgb32 = 17
	// FormatRgba32 as declared in nk/nuklear.h:5006
	FormatRgba32 = 18
	// FormatColorEnd as declared in nk/nuklear.h:5007
	FormatColorEnd = FormatRgba32
	// FormatCount as declared in nk/nuklear.h:5008
	FormatCount = 19
)

const (
	// StyleItemColor as declared in nk/nuklear.h:5102
	StyleItemColor = iota
	// StyleItemImage as declared in nk/nuklear.h:5103
	StyleItemImage = 1
	// StyleItemNineSlice as declared in nk/nuklear.h:5104
	StyleItemNineSlice = 2
)

const (
	// HeaderLeft as declared in nk/nuklear.h:5504
	HeaderLeft = iota
	// HeaderRight as declared in nk/nuklear.h:5505
	HeaderRight = 1
)

const (
	// PanelNone as declared in nk/nuklear.h:5612
	PanelNone = iota
	// PanelWindow as declared in nk/nuklear.h:5613
	PanelWindow = (1 << (0))
	// PanelGroup as declared in nk/nuklear.h:5614
	PanelGroup = (1 << (1))
	// PanelPopup as declared in nk/nuklear.h:5615
	PanelPopup = (1 << (2))
	// PanelContextual as declared in nk/nuklear.h:5616
	PanelContextual = (1 << (4))
	// PanelCombo as declared in nk/nuklear.h:5617
	PanelCombo = (1 << (5))
	// PanelMenu as declared in nk/nuklear.h:5618
	PanelMenu = (1 << (6))
	// PanelTooltip as declared in nk/nuklear.h:5619
	PanelTooltip = (1 << (7))
)

const (
	// PanelSetNonblock as declared in nk/nuklear.h:5622
	PanelSetNonblock = PanelContextual | PanelCombo | PanelMenu | PanelTooltip
	// PanelSetPopup as declared in nk/nuklear.h:5623
	PanelSetPopup = PanelSetNonblock | PanelPopup
	// PanelSetSub as declared in nk/nuklear.h:5624
	PanelSetSub = PanelSetPopup | PanelGroup
)

const (
	// LayoutDynamicFixed as declared in nk/nuklear.h:5645
	LayoutDynamicFixed = iota
	// LayoutDynamicRow as declared in nk/nuklear.h:5646
	LayoutDynamicRow = 1
	// LayoutDynamicFree as declared in nk/nuklear.h:5647
	LayoutDynamicFree = 2
	// LayoutDynamic as declared in nk/nuklear.h:5648
	LayoutDynamic = 3
	// LayoutStaticFixed as declared in nk/nuklear.h:5649
	LayoutStaticFixed = 4
	// LayoutStaticRow as declared in nk/nuklear.h:5650
	LayoutStaticRow = 5
	// LayoutStaticFree as declared in nk/nuklear.h:5651
	LayoutStaticFree = 6
	// LayoutStatic as declared in nk/nuklear.h:5652
	LayoutStatic = 7
	// LayoutTemplate as declared in nk/nuklear.h:5653
	LayoutTemplate = 8
	// LayoutCount as declared in nk/nuklear.h:5654
	LayoutCount = 9
)

const (
	// WindowPrivate as declared in nk/nuklear.h:5713
	WindowPrivate = (1 << (11))
	// WindowDynamic as declared in nk/nuklear.h:5714
	WindowDynamic = WindowPrivate
	// WindowRom as declared in nk/nuklear.h:5715
	WindowRom = (1 << (12))
	// WindowNotInteractive as declared in nk/nuklear.h:5716
	WindowNotInteractive = WindowRom | WindowNoInput
	// WindowHidden as declared in nk/nuklear.h:5717
	WindowHidden = (1 << (13))
	// WindowClosed as declared in nk/nuklear.h:5718
	WindowClosed = (1 << (14))
	// WindowMinimized as declared in nk/nuklear.h:5719
	WindowMinimized = (1 << (15))
	// WindowRemoveRom as declared in nk/nuklear.h:5720
	WindowRemoveRom = (1 << (16))
)
