// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 28 Oct 2025 01:24:27 -03.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package nk provides Go bindings for nuklear.h — a small ANSI C gui library.
*/
package nk
