// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 28 Oct 2025 01:24:27 -03.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package nk

/*
#include "nk.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Char type as declared in nk/nuklear.h:419
type Char int8

// Uchar type as declared in nk/nuklear.h:420
type Uchar byte

// Byte type as declared in nk/nuklear.h:421
type Byte byte

// Short type as declared in nk/nuklear.h:422
type Short int16

// Ushort type as declared in nk/nuklear.h:423
type Ushort uint16

// Int type as declared in nk/nuklear.h:424
type Int int32

// Uint type as declared in nk/nuklear.h:425
type Uint uint32

// Size type as declared in nk/nuklear.h:426
type Size uint64

// Ptr type as declared in nk/nuklear.h:427
type Ptr uint64

// Bool type as declared in nk/nuklear.h:428
type Bool int32

// Hash type as declared in nk/nuklear.h:430
type Hash uint32

// Flags type as declared in nk/nuklear.h:431
type Flags uint32

// Rune type as declared in nk/nuklear.h:432
type Rune uint32

// Glyph type as declared in nk/nuklear.h:490
type Glyph [4]byte

// Handle as declared in nk/nuklear.h:491
const sizeofHandle = unsafe.Sizeof(C.nk_handle{})

type Handle [sizeofHandle]byte

// PluginAlloc type as declared in nk/nuklear.h:510
type PluginAlloc func(arg0 Handle, old unsafe.Pointer, arg2 Size) unsafe.Pointer

// PluginFree type as declared in nk/nuklear.h:511
type PluginFree func(arg0 Handle, old unsafe.Pointer)

// PluginFilter type as declared in nk/nuklear.h:512
type PluginFilter func(arg0 *TextEdit, unicode Rune) Bool

// PluginPaste type as declared in nk/nuklear.h:513
type PluginPaste func(arg0 Handle, arg1 *TextEdit)

// PluginCopy type as declared in nk/nuklear.h:514
type PluginCopy func(arg0 Handle, arg1 *byte, len int32)

// TextWidthF type as declared in nk/nuklear.h:4215
type TextWidthF func(arg0 Handle, h float32, arg2 *byte, len int32) float32

// QueryFontGlyphF type as declared in nk/nuklear.h:4216
type QueryFontGlyphF func(handle Handle, fontHeight float32, glyph *UserFontGlyph, codepoint Rune, nextCodepoint Rune)

// CommandCustomCallback type as declared in nk/nuklear.h:4828
type CommandCustomCallback func(canvas unsafe.Pointer, x int16, y int16, w uint16, h uint16, callbackData Handle)

// DrawIndex type as declared in nk/nuklear.h:4969
type DrawIndex uint16

// Allocator as declared in nk/nuklear.h:458
type Allocator C.struct_nk_allocator

// BakedFont as declared in nk/nuklear.h:4246
type BakedFont C.struct_nk_baked_font

// Buffer as declared in nk/nuklear.h:457
type Buffer C.struct_nk_buffer

// BufferMarker as declared in nk/nuklear.h:4406
type BufferMarker C.struct_nk_buffer_marker

// Chart as declared in nk/nuklear.h:5638
type Chart C.struct_nk_chart

// ChartSlot as declared in nk/nuklear.h:5627
type ChartSlot C.struct_nk_chart_slot

// Clipboard as declared in nk/nuklear.h:4535
type Clipboard C.struct_nk_clipboard

// Color as declared in nk/nuklear.h:484
type Color C.struct_nk_color

// Colorf as declared in nk/nuklear.h:485
type Colorf C.struct_nk_colorf

// Command as declared in nk/nuklear.h:4690
type Command C.struct_nk_command

// CommandArc as declared in nk/nuklear.h:4780
type CommandArc C.struct_nk_command_arc

// CommandArcFilled as declared in nk/nuklear.h:4789
type CommandArcFilled C.struct_nk_command_arc_filled

// CommandBuffer as declared in nk/nuklear.h:459
type CommandBuffer C.struct_nk_command_buffer

// CommandCircle as declared in nk/nuklear.h:4765
type CommandCircle C.struct_nk_command_circle

// CommandCircleFilled as declared in nk/nuklear.h:4773
type CommandCircleFilled C.struct_nk_command_circle_filled

// CommandCurve as declared in nk/nuklear.h:4712
type CommandCurve C.struct_nk_command_curve

// CommandCustom as declared in nk/nuklear.h:4830
type CommandCustom C.struct_nk_command_custom

// CommandImage as declared in nk/nuklear.h:4820
type CommandImage C.struct_nk_command_image

// CommandLine as declared in nk/nuklear.h:4704
type CommandLine C.struct_nk_command_line

// CommandPolygon as declared in nk/nuklear.h:4797
type CommandPolygon C.struct_nk_command_polygon

// CommandPolygonFilled as declared in nk/nuklear.h:4805
type CommandPolygonFilled C.struct_nk_command_polygon_filled

// CommandPolyline as declared in nk/nuklear.h:4812
type CommandPolyline C.struct_nk_command_polyline

// CommandRect as declared in nk/nuklear.h:4721
type CommandRect C.struct_nk_command_rect

// CommandRectFilled as declared in nk/nuklear.h:4730
type CommandRectFilled C.struct_nk_command_rect_filled

// CommandRectMultiColor as declared in nk/nuklear.h:4738
type CommandRectMultiColor C.struct_nk_command_rect_multi_color

// CommandScissor as declared in nk/nuklear.h:4698
type CommandScissor C.struct_nk_command_scissor

// CommandText as declared in nk/nuklear.h:4838
type CommandText C.struct_nk_command_text

// CommandTriangle as declared in nk/nuklear.h:4748
type CommandTriangle C.struct_nk_command_triangle

// CommandTriangleFilled as declared in nk/nuklear.h:4757
type CommandTriangleFilled C.struct_nk_command_triangle_filled

// ConfigStackButtonBehavior as declared in nk/nuklear.h:5872
type ConfigStackButtonBehavior C.struct_nk_config_stack_button_behavior

// ConfigStackButtonBehaviorElement as declared in nk/nuklear.h:5864
type ConfigStackButtonBehaviorElement C.struct_nk_config_stack_button_behavior_element

// ConfigStackColor as declared in nk/nuklear.h:5870
type ConfigStackColor C.struct_nk_config_stack_color

// ConfigStackColorElement as declared in nk/nuklear.h:5862
type ConfigStackColorElement C.struct_nk_config_stack_color_element

// ConfigStackFlags as declared in nk/nuklear.h:5869
type ConfigStackFlags C.struct_nk_config_stack_flags

// ConfigStackFlagsElement as declared in nk/nuklear.h:5861
type ConfigStackFlagsElement C.struct_nk_config_stack_flags_element

// ConfigStackFloat as declared in nk/nuklear.h:5867
type ConfigStackFloat C.struct_nk_config_stack_float

// ConfigStackFloatElement as declared in nk/nuklear.h:5859
type ConfigStackFloatElement C.struct_nk_config_stack_float_element

// ConfigStackStyleItem as declared in nk/nuklear.h:5866
type ConfigStackStyleItem C.struct_nk_config_stack_style_item

// ConfigStackStyleItemElement as declared in nk/nuklear.h:5858
type ConfigStackStyleItemElement C.struct_nk_config_stack_style_item_element

// ConfigStackUserFont as declared in nk/nuklear.h:5871
type ConfigStackUserFont struct {
	Head           int32
	Elements       [8]ConfigStackUserFontElement
	refa664861d    *C.struct_nk_config_stack_user_font
	allocsa664861d interface{}
}

// ConfigStackUserFontElement as declared in nk/nuklear.h:5863
type ConfigStackUserFontElement struct {
	Address        [][]UserFont
	OldValue       []UserFont
	ref5572630c    *C.struct_nk_config_stack_user_font_element
	allocs5572630c interface{}
}

// ConfigStackVec2 as declared in nk/nuklear.h:5868
type ConfigStackVec2 C.struct_nk_config_stack_vec2

// ConfigStackVec2Element as declared in nk/nuklear.h:5860
type ConfigStackVec2Element C.struct_nk_config_stack_vec2_element

// ConfigurationStacks as declared in nk/nuklear.h:5874
type ConfigurationStacks C.struct_nk_configuration_stacks

// Context as declared in nk/nuklear.h:467
type Context C.struct_nk_context

// ConvertConfig as declared in nk/nuklear.h:461
type ConvertConfig struct {
	GlobalAlpha        float32
	CircleSegmentCount uint32
	ArcSegmentCount    uint32
	CurveSegmentCount  uint32
	TexNull            DrawNullTexture
	VertexLayout       []DrawVertexLayoutElement
	VertexSize         Size
	VertexAlignment    Size
	ref82bf4c25        *C.struct_nk_convert_config
	allocs82bf4c25     interface{}
}

// Cursor as declared in nk/nuklear.h:494
type Cursor C.struct_nk_cursor

// DrawCommand as declared in nk/nuklear.h:460
type DrawCommand C.struct_nk_draw_command

// DrawList as declared in nk/nuklear.h:464
type DrawList C.struct_nk_draw_list

// DrawNullTexture as declared in nk/nuklear.h:1197
type DrawNullTexture C.struct_nk_draw_null_texture

// DrawVertexLayoutElement as declared in nk/nuklear.h:468
type DrawVertexLayoutElement struct {
	Offset         Size
	refeb0614d6    *C.struct_nk_draw_vertex_layout_element
	allocseb0614d6 interface{}
}

// EditState as declared in nk/nuklear.h:5735
type EditState C.struct_nk_edit_state

// Font as declared in nk/nuklear.h:4245
type Font C.struct_nk_font

// FontAtlas as declared in nk/nuklear.h:4300
type FontAtlas C.struct_nk_font_atlas

// FontConfig as declared in nk/nuklear.h:4255
type FontConfig C.struct_nk_font_config

// FontGlyph as declared in nk/nuklear.h:4276
type FontGlyph C.struct_nk_font_glyph

// Image as declared in nk/nuklear.h:492
type Image C.struct_nk_image

// Input as declared in nk/nuklear.h:4922
type Input C.struct_nk_input

// Key as declared in nk/nuklear.h:4912
type Key C.struct_nk_key

// Keyboard as declared in nk/nuklear.h:4916
type Keyboard C.struct_nk_keyboard

// ListView as declared in nk/nuklear.h:3288
type ListView C.struct_nk_list_view

// Memory as declared in nk/nuklear.h:4411
type Memory C.struct_nk_memory

// MemoryStatus as declared in nk/nuklear.h:4386
type MemoryStatus C.struct_nk_memory_status

// MenuState as declared in nk/nuklear.h:5680
type MenuState C.struct_nk_menu_state

// Mouse as declared in nk/nuklear.h:4898
type Mouse C.struct_nk_mouse

// MouseButton as declared in nk/nuklear.h:4893
type MouseButton C.struct_nk_mouse_button

// NineSlice as declared in nk/nuklear.h:493
type NineSlice C.struct_nk_nine_slice

// Page as declared in nk/nuklear.h:5910
type Page C.struct_nk_page

// PageData as declared in nk/nuklear.h:5898
const sizeofPageData = unsafe.Sizeof(C.union_nk_page_data{})

type PageData [sizeofPageData]byte

// PageElement as declared in nk/nuklear.h:5904
type PageElement C.struct_nk_page_element

// Panel as declared in nk/nuklear.h:466
type Panel C.struct_nk_panel

// Pool as declared in nk/nuklear.h:5916
type Pool C.struct_nk_pool

// PopupBuffer as declared in nk/nuklear.h:5672
type PopupBuffer C.struct_nk_popup_buffer

// PopupState as declared in nk/nuklear.h:5723
type PopupState C.struct_nk_popup_state

// PropertyState as declared in nk/nuklear.h:5748
type PropertyState C.struct_nk_property_state

// Rect as declared in nk/nuklear.h:488
type Rect C.struct_nk_rect

// Recti as declared in nk/nuklear.h:489
type Recti C.struct_nk_recti

// RowLayout as declared in nk/nuklear.h:5656
type RowLayout C.struct_nk_row_layout

// Scroll as declared in nk/nuklear.h:495
type Scroll C.struct_nk_scroll

// Str as declared in nk/nuklear.h:4449
type Str C.struct_nk_str

// Style as declared in nk/nuklear.h:5569
type Style C.struct_nk_style

// StyleButton as declared in nk/nuklear.h:469
type StyleButton C.struct_nk_style_button

// StyleChart as declared in nk/nuklear.h:477
type StyleChart C.struct_nk_style_chart

// StyleCombo as declared in nk/nuklear.h:478
type StyleCombo C.struct_nk_style_combo

// StyleEdit as declared in nk/nuklear.h:475
type StyleEdit C.struct_nk_style_edit

// StyleItem as declared in nk/nuklear.h:462
type StyleItem C.struct_nk_style_item

// StyleItemData as declared in nk/nuklear.h:5107
const sizeofStyleItemData = unsafe.Sizeof(C.union_nk_style_item_data{})

type StyleItemData [sizeofStyleItemData]byte

// StyleKnob as declared in nk/nuklear.h:5265
type StyleKnob C.struct_nk_style_knob

// StyleProgress as declared in nk/nuklear.h:473
type StyleProgress C.struct_nk_style_progress

// StyleProperty as declared in nk/nuklear.h:476
type StyleProperty C.struct_nk_style_property

// StyleScrollbar as declared in nk/nuklear.h:474
type StyleScrollbar C.struct_nk_style_scrollbar

// StyleSelectable as declared in nk/nuklear.h:471
type StyleSelectable C.struct_nk_style_selectable

// StyleSlide as declared in nk/nuklear.h:472
type StyleSlide C.struct_nk_style_slide

// StyleSlider as declared in nk/nuklear.h:5224
type StyleSlider C.struct_nk_style_slider

// StyleTab as declared in nk/nuklear.h:479
type StyleTab C.struct_nk_style_tab

// StyleText as declared in nk/nuklear.h:5118
type StyleText C.struct_nk_style_text

// StyleToggle as declared in nk/nuklear.h:470
type StyleToggle C.struct_nk_style_toggle

// StyleWindow as declared in nk/nuklear.h:481
type StyleWindow C.struct_nk_style_window

// StyleWindowHeader as declared in nk/nuklear.h:480
type StyleWindowHeader C.struct_nk_style_window_header

// Table as declared in nk/nuklear.h:5711
type Table C.struct_nk_table

// TextEdit as declared in nk/nuklear.h:463
type TextEdit C.struct_nk_text_edit

// TextUndoRecord as declared in nk/nuklear.h:4541
type TextUndoRecord C.struct_nk_text_undo_record

// TextUndoState as declared in nk/nuklear.h:4548
type TextUndoState C.struct_nk_text_undo_state

// UserFont as declared in nk/nuklear.h:465
type UserFont struct {
	Userdata       Handle
	Height         float32
	Width          TextWidthF
	Query          QueryFontGlyphF
	Texture        Handle
	ref738ce62e    *C.struct_nk_user_font
	allocs738ce62e interface{}
}

// UserFontGlyph as declared in nk/nuklear.h:4214
type UserFontGlyph struct {
	Uv             [2]Vec2
	Offset         Vec2
	Width          float32
	Height         float32
	Xadvance       float32
	ref4a84b297    *C.struct_nk_user_font_glyph
	allocs4a84b297 interface{}
}

// Vec2 as declared in nk/nuklear.h:486
type Vec2 C.struct_nk_vec2

// Vec2i as declared in nk/nuklear.h:487
type Vec2i C.struct_nk_vec2i

// Window as declared in nk/nuklear.h:5761
type Window C.struct_nk_window
